name: wisebu
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  clippy_flutter: ^1.1.1
  intl: ^0.16.1
  sqflite: ^1.3.1+1
  shared_preferences: ^0.5.10
  flushbar: ^1.10.4
  path_provider: ^0.5.0+1
  flutter_device_type: ^0.3.2

  flutter:
    sdk: flutter

  # firebase dependencies
  firebase_core: ^0.5.3
  firebase_analytics: ^6.3.0
  firebase_crashlytics: ^0.2.4

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/images/
  fonts:
    - family: Spartan
      fonts:
        - asset: lib/fonts/Spartan.ttf
