name: wisebu
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  clippy_flutter: ^2.0.0-nullsafety.1
  intl: ^0.17.0
  sqflite: ^2.0.2
  shared_preferences: ^2.0.13
  another_flushbar: ^1.10.28
  path_provider: ^2.0.9

  flutter:
    sdk: flutter

  # firebase dependencies
  firebase_core: ^1.12.0
  firebase_analytics: ^9.1.0
  firebase_crashlytics: ^2.5.1

  cupertino_icons: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/images/
  fonts:
    - family: Spartan
      fonts:
        - asset: lib/fonts/Spartan.ttf
